// ─── Grade 2 · Stage 1: Maker — All 10 Lessons ──────────────────────────────

export const GRADE2_MAKER_LESSONS = [
  // ── Lesson 1 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a8023",
    accentColor: "#4F46E5",
    badge: "Grade 2 · Lesson 1 of 10 · Maker Stage",
    typeBadge: "Reading",
    title: "Shapes Used in Objects",
    subtitle: "Identify and name the 2D and 3D shapes hiding inside everyday objects around you.",
    readings: [
      {
        svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="20" fill="#EEF2FF" stroke="#4F46E5" stroke-width="2.5"></circle><rect x="14" y="14" width="10" height="10" rx="1" fill="#4F46E5" opacity=".5"></rect><polygon points="30,14 44,38 16,38" fill="#4F46E5" opacity=".8"></polygon></svg>`,
        heading: "Shapes are everywhere — if you look closely",
        body: "Every object you can see is made up of one or more shapes. A bicycle has circles (wheels), rectangles (frame), and cylinders (handles). Learning to see shapes inside objects is one of the first skills of a designer.",
      },
      {
        svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="28" width="20" height="20" rx="2" fill="#4F46E5"></rect><polygon points="14,6 26,28 2,28" fill="#818CF8"></polygon><circle cx="38" cy="18" r="14" fill="#4F46E5" opacity=".4" stroke="#4F46E5" stroke-width="2"></circle></svg>`,
        heading: "2D shapes become 3D objects",
        body: "When a flat 2D shape is extended into space, it becomes a 3D solid. A circle becomes a sphere or cylinder. A square becomes a cube. A triangle becomes a pyramid or cone. This transformation from flat to solid is how designers think when they build.",
      },
      {
        svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="16" cy="26" r="12" fill="#4F46E5" opacity=".5"></circle><rect x="28" y="10" width="20" height="32" rx="3" fill="#4F46E5"></rect><line x1="28" y1="26" x2="16" y2="26" stroke="#C7D2FE" stroke-width="2" stroke-dasharray="3 2"></line></svg>`,
        heading: "Simple vs composite objects",
        body: "A simple object is made of just one shape (like a ball = sphere). A composite object is made of two or more shapes joined together (like a house = rectangle + triangle). Most real objects are composite — designers combine shapes creatively.",
      },
      {
        svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><polygon points="26,4 50,48 2,48" fill="#4F46E5" opacity=".3" stroke="#4F46E5" stroke-width="2"></polygon><text x="26" y="42" text-anchor="middle" font-size="10" font-weight="800" fill="#4F46E5" font-family="Nunito,sans-serif">PRISM</text><circle cx="40" cy="14" r="10" fill="#4F46E5" opacity=".5"></circle><text x="40" y="18" text-anchor="middle" font-size="8" font-weight="800" fill="white" font-family="Nunito,sans-serif">CONE</text></svg>`,
        heading: "Designers use shape language",
        body: `When designers describe objects to builders, they use shape names precisely. Instead of saying "the round part on top," they say "the hemisphere on the upper surface." Learning shape vocabulary helps you communicate your ideas clearly and professionally.`,
      },
    ],
    revealLabel: "Explore — tap to see what shapes make each object",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="8" y="24" width="36" height="24" rx="2" fill="#4F46E5"></rect><polygon points="26,4 48,24 4,24" fill="#818CF8"></polygon><rect x="20" y="34" width="12" height="14" rx="1" fill="white" opacity=".5"></rect></svg>`, name: "House", desc: "Rectangle walls + Triangle roof + Rectangle door + Square windows. 4 shapes in one object!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="26" width="44" height="18" rx="4" fill="#4F46E5" opacity=".7"></rect><rect x="14" y="16" width="22" height="14" rx="3" fill="#818CF8"></rect><circle cx="14" cy="44" r="7" fill="#312E81"></circle><circle cx="38" cy="44" r="7" fill="#312E81"></circle></svg>`, name: "Car", desc: "Rectangle body + Rectangle roof + 2 Circle wheels. Always look for repeated shapes!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="8" y="14" width="36" height="28" fill="#4F46E5"></rect><ellipse cx="26" cy="14" rx="18" ry="7" fill="#818CF8"></ellipse><ellipse cx="26" cy="42" rx="18" ry="7" fill="#312E81"></ellipse></svg>`, name: "Can / Cup", desc: "Cylinder = rectangle (curved around) + 2 circles (top and bottom). One 3D shape made from 2D shapes!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="20" y="8" width="12" height="30" rx="4" fill="#4F46E5"></rect><polygon points="20,38 32,38 26,48" fill="#312E81"></polygon><rect x="20" y="8" width="12" height="8" rx="4" fill="#818CF8"></rect></svg>`, name: "Pencil", desc: "Long rectangle body + Triangle tip + Small rectangle eraser cap. 3 shapes!" },
    ],
    dragLabel: "Activity — match the object to the shapes that build it",
    dragChips: [
      { label: "Rectangle + Triangle", val: "Rectangle + Triangle" },
      { label: "2 Circles + Rectangle", val: "2 Circles + Rectangle" },
      { label: "Rectangle + 2 Circles", val: "Rectangle + 2 Circles" },
      { label: "Sphere", val: "Sphere" },
    ],
    dragZones: [
      { answer: "Rectangle + Triangle", label: "House", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="4" y="18" width="28" height="16" rx="2" fill="none" stroke="#A5B4FC" stroke-width="2"></rect><polygon points="18,3 32,18 4,18" fill="none" stroke="#A5B4FC" stroke-width="2"></polygon></svg>` },
      { answer: "Sphere", label: "Ball", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="18" r="13" fill="none" stroke="#A5B4FC" stroke-width="2"></circle><ellipse cx="18" cy="18" rx="6" ry="13" fill="none" stroke="#A5B4FC" stroke-width="1" stroke-dasharray="3 2"></ellipse></svg>` },
      { answer: "2 Circles + Rectangle", label: "Can", svgContent: `<svg width="32" height="36" viewBox="0 0 32 36"><rect x="2" y="8" width="28" height="22" fill="none" stroke="#A5B4FC" stroke-width="2"></rect><ellipse cx="16" cy="8" rx="14" ry="5" fill="none" stroke="#A5B4FC" stroke-width="1.5"></ellipse><ellipse cx="16" cy="30" rx="14" ry="5" fill="none" stroke="#A5B4FC" stroke-width="1.5"></ellipse></svg>` },
      { answer: "Rectangle + 2 Circles", label: "Car", svgContent: `<svg width="36" height="28" viewBox="0 0 36 28"><rect x="2" y="6" width="32" height="16" rx="3" fill="none" stroke="#A5B4FC" stroke-width="2"></rect><circle cx="9" cy="22" r="5" fill="none" stroke="#A5B4FC" stroke-width="2"></circle><circle cx="27" cy="22" r="5" fill="none" stroke="#A5B4FC" stroke-width="2"></circle></svg>` },
    ],
    quizLabel: "Quiz — 4 questions, think carefully!",
    quiz: [
      { text: "A composite object is made of…", options: [{ label: "One shape only", correct: false }, { label: "Two or more shapes joined", correct: true }, { label: "Only 3D shapes", correct: false }, { label: "Shapes that cannot be drawn", correct: false }] },
      { text: "Which 3D shape does a CIRCLE become when given depth?", options: [{ label: "Cube", correct: false }, { label: "Pyramid", correct: false }, { label: "Cylinder or Sphere", correct: true }, { label: "Rectangle", correct: false }] },
      { text: "A pencil has a triangle tip. What does that triangle become in 3D?", options: [{ label: "Cylinder", correct: false }, { label: "Cube", correct: false }, { label: "Sphere", correct: false }, { label: "Cone", correct: true }] },
      { text: "Why do designers use shape vocabulary precisely?", options: [{ label: "To sound impressive", correct: false }, { label: "To communicate ideas clearly to builders", correct: true }, { label: "Because it is required by law", correct: false }, { label: "To make drawings look better", correct: false }] },
    ],
  },

  // ── Lesson 2 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a8024",
    accentColor: "#0369A1",
    badge: "Grade 2 · Lesson 2 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Parts of Everyday Objects",
    subtitle: "Break objects down into their parts and identify the function of each part.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="12" y="28" width="28" height="18" rx="2" fill="#0369A1"></rect><rect x="14" y="18" width="8" height="12" rx="1" fill="#0369A1" opacity=".6"></rect><rect x="30" y="18" width="8" height="12" rx="1" fill="#0369A1" opacity=".6"></rect><rect x="10" y="8" width="32" height="12" rx="3" fill="#7DD3FC"></rect></svg>`, heading: "Every object has parts with jobs", body: "A chair has legs (to hold it up), a seat (to sit on), and a back (to lean against). Each part has a specific function. Designers think about what each part must DO before they decide what shape it should be." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="20" fill="#E0F2FE" stroke="#0369A1" stroke-width="2.5"></circle><text x="26" y="22" text-anchor="middle" font-size="9" font-weight="800" fill="#0369A1" font-family="Nunito,sans-serif">FORM</text><line x1="26" y1="24" x2="26" y2="30" stroke="#0369A1" stroke-width="2"></line><text x="26" y="40" text-anchor="middle" font-size="9" font-weight="800" fill="#0369A1" font-family="Nunito,sans-serif">FUNCTION</text></svg>`, heading: "Form follows function", body: '"Form follows function" is a famous design principle. It means the shape (form) of a part should match what it needs to do (function). A wheel is round because rolling requires a round shape. A shelf is flat because things must sit on it without falling.' },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="18" width="20" height="28" rx="3" fill="#0369A1" opacity=".6"></rect><rect x="28" y="18" width="20" height="28" rx="3" fill="#0369A1" opacity=".6"></rect><rect x="14" y="8" width="24" height="14" rx="2" fill="#0369A1"></rect><line x1="24" y1="20" x2="28" y2="20" stroke="#7DD3FC" stroke-width="3" stroke-linecap="round"></line></svg>`, heading: "Parts must work together", body: "Individual parts are designed to fit together precisely. A door must fit its frame. A lid must fit its box. Designers use measurements to make sure parts connect properly. When parts fit well together, we say the object has good assembly." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="20" fill="#E0F2FE" stroke="#0369A1" stroke-width="2"></circle><text x="26" y="20" text-anchor="middle" font-size="8" font-weight="700" fill="#0369A1" font-family="Nunito,sans-serif">ANALYZE</text><line x1="14" y1="26" x2="38" y2="26" stroke="#0369A1" stroke-width="1.5"></line><text x="26" y="36" text-anchor="middle" font-size="8" font-weight="700" fill="#0369A1" font-family="Nunito,sans-serif">REDESIGN</text></svg>`, heading: "Analyzing objects like a designer", body: "Designers use object analysis to study existing products. They ask: What are all the parts? What shape is each part? What does each part do? Could any part be improved? This critical thinking skill is used throughout the entire design profession." },
    ],
    revealLabel: "Explore — tap each card to learn about object parts",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="12" y="28" width="28" height="18" rx="2" fill="#0369A1"></rect><rect x="14" y="18" width="8" height="12" rx="1" fill="#0369A1" opacity=".6"></rect><rect x="30" y="18" width="8" height="12" rx="1" fill="#0369A1" opacity=".6"></rect><rect x="10" y="8" width="32" height="12" rx="3" fill="#7DD3FC"></rect></svg>`, name: "Chair parts", desc: "Legs (support) + Seat (surface to sit on) + Back (for leaning). Each part has one clear function!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><ellipse cx="18" cy="26" rx="12" ry="6" fill="#0369A1" opacity=".7"></ellipse><ellipse cx="34" cy="26" rx="12" ry="6" fill="#0369A1" opacity=".7"></ellipse><circle cx="26" cy="26" r="4" fill="#7DD3FC"></circle><rect x="14" y="10" width="8" height="18" rx="3" fill="#075985"></rect><rect x="30" y="10" width="8" height="18" rx="3" fill="#075985"></rect></svg>`, name: "Scissors parts", desc: "Blades (cut) + Pivot screw (holds blades together) + Handles (grip). All 3 parts must work together!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="8" width="40" height="28" rx="3" fill="#0369A1"></rect><rect x="8" y="10" width="36" height="24" rx="2" fill="#E0F2FE"></rect><rect x="18" y="36" width="16" height="6" rx="1" fill="#0369A1" opacity=".7"></rect><rect x="10" y="42" width="32" height="6" rx="3" fill="#075985"></rect></svg>`, name: "Monitor parts", desc: "Screen (display) + Stand (support) + Base (balance). Remove any part and it stops working!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="8" width="40" height="28" rx="3" fill="#E0F2FE" stroke="#0369A1" stroke-width="2"></rect><line x1="12" y1="16" x2="40" y2="16" stroke="#0369A1" stroke-width="1.5"></line><line x1="12" y1="21" x2="32" y2="21" stroke="#7DD3FC" stroke-width="1.5"></line><text x="8" y="34" font-size="8" font-weight="700" fill="#0369A1" font-family="Nunito,sans-serif">LABEL ← PART</text></svg>`, name: "Object analysis", desc: "Designers draw all the parts with labels showing what each part does. This is called a labeled diagram." },
    ],
    dragLabel: "Activity — match each part to its function",
    dragChips: [
      { label: "Support weight", val: "Support weight" },
      { label: "Roll smoothly", val: "Roll smoothly" },
      { label: "Hold grip", val: "Hold grip" },
      { label: "Cut material", val: "Cut material" },
    ],
    dragZones: [
      { answer: "Support weight", label: "Chair legs", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="4" y="20" width="28" height="4" rx="1" fill="#7DD3FC"></rect><rect x="8" y="24" width="4" height="10" rx="1" fill="#7DD3FC"></rect><rect x="24" y="24" width="4" height="10" rx="1" fill="#7DD3FC"></rect></svg>` },
      { answer: "Roll smoothly", label: "Car wheel", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="18" r="13" fill="none" stroke="#7DD3FC" stroke-width="2.5"></circle><circle cx="18" cy="18" r="5" fill="#7DD3FC"></circle></svg>` },
      { answer: "Hold grip", label: "Scissors handle", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><ellipse cx="18" cy="20" rx="10" ry="14" fill="none" stroke="#7DD3FC" stroke-width="2"></ellipse><ellipse cx="18" cy="20" rx="5" ry="9" fill="none" stroke="#7DD3FC" stroke-width="1.5" stroke-dasharray="3 2"></ellipse></svg>` },
      { answer: "Cut material", label: "Knife blade", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><polygon points="4,30 32,8 32,20 4,32" fill="none" stroke="#7DD3FC" stroke-width="2"></polygon></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "What does 'form follows function' mean?", options: [{ label: "Make things look good first", correct: false }, { label: "Shape should match what the part needs to do", correct: true }, { label: "Function is more important than form", correct: false }, { label: "Forms follow each other in a line", correct: false }] },
      { text: "Why is a wheel ROUND?", options: [{ label: "Round shapes look nice", correct: false }, { label: "Wheels are always round by tradition", correct: false }, { label: "Rolling requires a round shape", correct: true }, { label: "Rectangles are too heavy", correct: false }] },
      { text: "What is 'object analysis'?", options: [{ label: "Painting an object different colors", correct: false }, { label: "Studying an object's parts and their functions", correct: true }, { label: "Breaking an object by force", correct: false }, { label: "Counting how many objects you own", correct: false }] },
      { text: "A shelf is flat because…", options: [{ label: "Flat is cheaper to make", correct: false }, { label: "Things must sit on it without falling", correct: true }, { label: "Designers prefer flat shapes", correct: false }, { label: "Shelves are always flat by rule", correct: false }] },
    ],
  },

  // ── Lesson 3 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a8025",
    accentColor: "#059669",
    badge: "Grade 2 · Lesson 3 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Combining Shapes to Build Tools",
    subtitle: "Design functional tools by combining basic shapes — and understand WHY each shape is chosen.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="20" y="6" width="12" height="32" rx="2" fill="#D1FAE5" stroke="#059669" stroke-width="2"></rect><rect x="4" y="16" width="44" height="12" rx="3" fill="#059669"></rect></svg>`, heading: "Tools are designed, not accidental", body: "Every tool — hammer, scissors, fork, spoon — was designed by someone who thought carefully about shapes. The shape of a tool determines how well it works. A round spoon holds liquid. A pointy fork pierces food. Shape choices have consequences." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="8" width="20" height="20" rx="3" fill="#059669"></rect><rect x="22" y="18" width="26" height="8" rx="4" fill="#6EE7B7"></rect></svg>`, heading: "Why hammers have that shape", body: "A hammer head is a heavy cylinder (to deliver force). The handle is a long rectangle/cylinder (to multiply force through leverage). The flat face hits nails. Every part of a hammer's shape is there for a reason — nothing is accidental." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><polygon points="26,4 50,48 2,48" fill="#059669"></polygon><line x1="14" y1="34" x2="26" y2="4" stroke="#D1FAE5" stroke-width="1.5"></line><line x1="38" y1="34" x2="26" y2="4" stroke="#D1FAE5" stroke-width="1.5"></line><line x1="14" y1="34" x2="38" y2="34" stroke="#D1FAE5" stroke-width="1.5"></line></svg>`, heading: "Triangles add strength", body: "Triangles are the strongest shape in construction. When force pushes on a triangle, it distributes the force along all three sides instead of one point. That is why bridges, cranes, and tool handles often include triangular structures." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="12" cy="26" r="9" fill="#059669" opacity=".5"></circle><line x1="20" y1="26" x2="30" y2="26" stroke="#059669" stroke-width="2" stroke-dasharray="3 2"></line><circle cx="40" cy="26" r="9" fill="#059669"></circle><text x="40" y="30" text-anchor="middle" font-size="8" font-weight="800" fill="white" font-family="Nunito,sans-serif">V2</text></svg>`, heading: "Iteration: improving tool designs", body: "The first version of any tool is rarely perfect. Designers test, notice problems, and improve — this process is called iteration. Early spoons were flat sticks. After many iterations, the curved bowl shape was developed because it holds food better." },
    ],
    revealLabel: "Explore — tap to see how shapes create tool functions",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="8" width="20" height="20" rx="3" fill="#059669"></rect><rect x="22" y="18" width="26" height="8" rx="4" fill="#6EE7B7"></rect></svg>`, name: "Hammer", desc: "Heavy cube head (delivers force) + Long cylinder handle (leverage). Shape = power!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><ellipse cx="18" cy="22" rx="12" ry="10" fill="#059669"></ellipse><rect x="28" y="18" width="20" height="8" rx="4" fill="#6EE7B7"></rect></svg>`, name: "Spoon", desc: "Round bowl (holds liquid) + Narrow handle (easy to grip). Each part chosen for function!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><polygon points="10,48 42,48 10,8" fill="#059669"></polygon><polygon points="10,48 42,48 42,8" fill="#047857" opacity=".5"></polygon></svg>`, name: "Wedge / Axe", desc: "Triangle wedge shape splits force to both sides — like an axe blade or door wedge!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="14" cy="26" r="10" fill="#059669" opacity=".4" stroke="#059669" stroke-width="2"></circle><line x1="24" y1="26" x2="30" y2="26" stroke="#059669" stroke-width="2.5" stroke-dasharray="3 2"></line><circle cx="40" cy="26" r="10" fill="#059669"></circle></svg>`, name: "Iteration", desc: "Version 1 → Test → Improve → Version 2. Better tools come from many rounds of testing and fixing!" },
    ],
    dragLabel: "Activity — match each tool shape to its function",
    dragChips: [
      { label: "Delivers force", val: "Delivers force" },
      { label: "Holds liquid", val: "Holds liquid" },
      { label: "Splits material", val: "Splits material" },
      { label: "Provides grip", val: "Provides grip" },
    ],
    dragZones: [
      { answer: "Delivers force", label: "Hammer head", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="4" y="8" width="18" height="18" rx="2" fill="none" stroke="#6EE7B7" stroke-width="2"></rect><text x="13" y="20" text-anchor="middle" font-size="9" fill="#6EE7B7" font-weight="700" font-family="Nunito,sans-serif">⚒</text></svg>` },
      { answer: "Holds liquid", label: "Spoon bowl", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><ellipse cx="18" cy="20" rx="12" ry="10" fill="none" stroke="#6EE7B7" stroke-width="2"></ellipse></svg>` },
      { answer: "Splits material", label: "Axe blade", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><polygon points="6,34 30,34 6,4" fill="none" stroke="#6EE7B7" stroke-width="2"></polygon></svg>` },
      { answer: "Provides grip", label: "Tool handle", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="14" y="4" width="8" height="28" rx="4" fill="none" stroke="#6EE7B7" stroke-width="2"></rect></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "Why is a spoon bowl ROUND and curved?", options: [{ label: "Round shapes look nice", correct: false }, { label: "It is easier to manufacture", correct: false }, { label: "A curved bowl holds food and liquid without spilling", correct: true }, { label: "Flat bowls are too heavy", correct: false }] },
      { text: "Why are triangles used in construction and tools?", options: [{ label: "Triangles are the most common shape", correct: false }, { label: "Triangles are the strongest shape — they distribute force", correct: true }, { label: "Triangles are cheap to make", correct: false }, { label: "Designers prefer triangles aesthetically", correct: false }] },
      { text: "What is 'iteration' in design?", options: [{ label: "Drawing the same design twice", correct: false }, { label: "Testing and improving a design through multiple versions", correct: true }, { label: "Copying an existing product", correct: false }, { label: "Presenting your design to a client", correct: false }] },
      { text: "A hammer handle is long because…", options: [{ label: "Long handles look more professional", correct: false }, { label: "A longer handle creates more leverage and force", correct: true }, { label: "Short handles are too expensive", correct: false }, { label: "Long handles are easier to store", correct: false }] },
    ],
  },

  // ── Lesson 4 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a8026",
    accentColor: "#D97706",
    badge: "Grade 2 · Lesson 4 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Drawing Functional Objects",
    subtitle: "Learn to draw objects that show not just how they look — but how they WORK.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="4" width="44" height="44" rx="4" fill="#FEF3C7" stroke="#D97706" stroke-width="2"></rect><line x1="10" y1="14" x2="42" y2="14" stroke="#D97706" stroke-width="1.5"></line><line x1="10" y1="20" x2="34" y2="20" stroke="#FCD34D" stroke-width="1.5"></line><line x1="10" y1="26" x2="38" y2="26" stroke="#FCD34D" stroke-width="1.5"></line><text x="10" y="38" font-size="8" font-weight="700" fill="#D97706" font-family="Nunito,sans-serif">FUNCTIONAL</text></svg>`, heading: "Functional drawings vs decorative drawings", body: "A decorative drawing makes something look beautiful. A functional drawing shows how something works — it includes measurements, labels, arrows showing movement, and notes about materials. Engineers and product designers use functional drawings every day." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="8" y="14" width="28" height="24" rx="2" fill="#FEF3C7" stroke="#D97706" stroke-width="2"></rect><line x1="36" y1="22" x2="46" y2="18" stroke="#D97706" stroke-width="1.5"></line><line x1="36" y1="30" x2="46" y2="34" stroke="#D97706" stroke-width="1.5"></line><circle cx="46" cy="18" r="2.5" fill="#D97706"></circle><circle cx="46" cy="34" r="2.5" fill="#D97706"></circle></svg>`, heading: "Labels and annotations", body: `In a functional drawing, every important part is labeled with its name and function. An arrow pointing to the wheel says "wheel — allows rolling." This is called annotation. A drawing without labels is like a map without street names.` },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="4" width="20" height="14" rx="2" fill="#D97706" opacity=".7"></rect><text x="14" y="14" text-anchor="middle" font-size="7" fill="white" font-weight="700" font-family="Nunito,sans-serif">FRONT</text><rect x="28" y="4" width="20" height="14" rx="2" fill="#D97706" opacity=".5"></rect><text x="38" y="14" text-anchor="middle" font-size="7" fill="white" font-weight="700" font-family="Nunito,sans-serif">SIDE</text><rect x="4" y="22" width="20" height="14" rx="2" fill="#D97706" opacity=".3"></rect><text x="14" y="32" text-anchor="middle" font-size="7" fill="#D97706" font-weight="700" font-family="Nunito,sans-serif">TOP</text></svg>`, heading: "Top view, side view, front view", body: "A 3D object looks different from different angles. Designers draw three views: the front, the side, and the top. Together, these three views give a complete picture of the object. This is called multiview drawing." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><line x1="6" y1="46" x2="46" y2="6" stroke="#D97706" stroke-width="2.5" stroke-linecap="round"></line><circle cx="10" cy="42" r="4" fill="#D97706" opacity=".5"></circle><circle cx="26" cy="26" r="4" fill="#D97706" opacity=".7"></circle><circle cx="42" cy="10" r="4" fill="#D97706"></circle></svg>`, heading: "Sketching is thinking on paper", body: "Professional designers sketch constantly — not to make perfect art, but to think through ideas. A rough sketch with labels and arrows communicates more than a beautiful drawing with no explanation. Speed and clarity matter more than artistic skill." },
    ],
    revealLabel: "Explore — tap to see types of functional drawings",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="8" y="10" width="28" height="32" rx="2" fill="#FEF3C7" stroke="#D97706" stroke-width="2"></rect><line x1="36" y1="18" x2="46" y2="14" stroke="#D97706" stroke-width="1.5"></line><line x1="36" y1="26" x2="46" y2="26" stroke="#D97706" stroke-width="1.5"></line><line x1="36" y1="34" x2="46" y2="38" stroke="#D97706" stroke-width="1.5"></line><circle cx="46" cy="14" r="2" fill="#D97706"></circle><circle cx="46" cy="26" r="2" fill="#D97706"></circle><circle cx="46" cy="38" r="2" fill="#D97706"></circle></svg>`, name: "Labeled diagram", desc: "All parts are named with lines pointing to them. Shows WHAT each part is called." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="14" width="40" height="28" rx="3" fill="#FEF3C7" stroke="#D97706" stroke-width="2"></rect><line x1="20" y1="14" x2="10" y2="6" stroke="#D97706" stroke-width="1.5" stroke-dasharray="3 2"></line><text x="6" y="5" font-size="7" fill="#D97706" font-weight="700" font-family="Nunito,sans-serif">NOTE</text></svg>`, name: "Callout drawing", desc: "Lines with notes pointing to parts — used in instruction manuals!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="2" y="2" width="22" height="16" rx="2" fill="#D97706" opacity=".7"></rect><text x="13" y="13" text-anchor="middle" font-size="7" fill="white" font-weight="700" font-family="Nunito,sans-serif">FRONT</text><rect x="28" y="2" width="22" height="16" rx="2" fill="#D97706" opacity=".5"></rect><text x="39" y="13" text-anchor="middle" font-size="7" fill="white" font-weight="700" font-family="Nunito,sans-serif">SIDE</text><rect x="2" y="22" width="22" height="16" rx="2" fill="#D97706" opacity=".3"></rect><text x="13" y="33" text-anchor="middle" font-size="7" fill="#D97706" font-weight="700" font-family="Nunito,sans-serif">TOP</text></svg>`, name: "3-view drawing", desc: "Front + Side + Top views — gives a complete picture of a 3D object!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="8" y="12" width="36" height="28" rx="2" fill="#FEF3C7" stroke="#D97706" stroke-width="2"></rect><line x1="8" y1="26" x2="44" y2="26" stroke="#D97706" stroke-width="1" stroke-dasharray="3 2"></line><text x="26" y="22" text-anchor="middle" font-size="8" fill="#D97706" font-weight="700" font-family="Nunito,sans-serif">← 36mm →</text><text x="46" y="26" font-size="7" fill="#D97706" font-weight="700" font-family="Nunito,sans-serif">↕</text></svg>`, name: "Dimensioned sketch", desc: "Numbers show the size of each part. This lets someone else build exactly what you designed!" },
    ],
    dragLabel: "Put these drawing steps in the correct order",
    dragChips: [
      { label: "Choose the object", val: "Choose the object" },
      { label: "Sketch the outline", val: "Sketch the outline" },
      { label: "Add all parts", val: "Add all parts" },
      { label: "Label and annotate", val: "Label and annotate" },
    ],
    dragZones: [
      { answer: "Choose the object", label: "Step 1", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#D97706"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>` },
      { answer: "Sketch the outline", label: "Step 2", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#D97706"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>` },
      { answer: "Add all parts", label: "Step 3", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#D97706"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>` },
      { answer: "Label and annotate", label: "Step 4", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#D97706"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">4</text></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "What is the difference between a decorative and a functional drawing?", options: [{ label: "Decorative uses more colors", correct: false }, { label: "Functional shows how something works with labels and measurements", correct: true }, { label: "Decorative is drawn by artists only", correct: false }, { label: "Functional drawings are always digital", correct: false }] },
      { text: "Why do designers draw THREE views (front, side, top)?", options: [{ label: "To fill more pages", correct: false }, { label: "Because 3 is a lucky number", correct: false }, { label: "To give a complete picture of a 3D object from all angles", correct: true }, { label: "Front view alone is not interesting enough", correct: false }] },
      { text: "What is an 'annotation' in a drawing?", options: [{ label: "A color added to make it pretty", correct: false }, { label: "A label or note that explains a part", correct: true }, { label: "The size measurement of the object", correct: false }, { label: "The border around the drawing", correct: false }] },
      { text: "In professional design, which matters more in a sketch?", options: [{ label: "Artistic beauty", correct: false }, { label: "Perfect straight lines", correct: false }, { label: "Speed and clarity of communication", correct: true }, { label: "Using the most detail possible", correct: false }] },
    ],
  },

  // ── Lesson 5 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a8027",
    accentColor: "#7C3AED",
    badge: "Grade 2 · Lesson 5 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Simple Design Thinking",
    subtitle: "Apply the 5-step design thinking process to solve a real problem — like a real designer.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>`, heading: "Step 1 — Empathize: understand the user", body: "Design thinking starts with people, not ideas. Before designing anything, you observe and talk to the people who will use your product. What are their problems? What frustrates them? What do they need that they don't have? This is called empathy research." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>`, heading: "Step 2 — Define: name the problem clearly", body: `After observing users, you write a clear problem statement. Not "students need something better" but "Grade 2 students need a way to carry 4 books comfortably without straps hurting their shoulders." Specific problem statements lead to better solutions.` },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>`, heading: "Steps 3–5 — Ideate, Prototype, Test", body: "Ideate: generate MANY ideas — even silly ones. Prototype: build a quick, rough model of your best idea. Test: show it to real users and get feedback. Then go back and improve. Great designs go through this loop many times." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="18" fill="none" stroke="#7C3AED" stroke-width="3"></circle><polygon points="26,8 30,20 44,20 33,28 37,42 26,34 15,42 19,28 8,20 22,20" fill="#7C3AED" opacity=".4"></polygon></svg>`, heading: "Design thinking is not linear", body: "Real designers do not follow steps 1→5 in a straight line. They jump back and forth: test, discover a new problem, redefine, ideate again. This circular, flexible process is what makes design thinking so powerful for solving complex problems." },
    ],
    revealLabel: "Explore — tap to learn each design thinking step",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>`, name: "Empathize", desc: "Watch and listen to users. What problems do they have? What do they feel? Do not guess — observe!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>`, name: "Define", desc: 'Write one clear sentence: "Users need a way to [do something] because [reason]."' },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>`, name: "Ideate", desc: "Sketch 5 or more different ideas. The best idea is rarely the first one!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">4</text></svg>`, name: "Prototype & Test", desc: "Build a quick model. Show it to users. Listen to their feedback. Improve it!" },
    ],
    dragLabel: "Put the design thinking steps in the correct order",
    dragChips: [
      { label: "Empathize", val: "Empathize" },
      { label: "Define", val: "Define" },
      { label: "Ideate", val: "Ideate" },
      { label: "Prototype", val: "Prototype" },
    ],
    dragZones: [
      { answer: "Empathize", label: "Step 1", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>` },
      { answer: "Define", label: "Step 2", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>` },
      { answer: "Ideate", label: "Step 3", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>` },
      { answer: "Prototype", label: "Step 4", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">4</text></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "Why does design thinking START with empathy (not ideas)?", options: [{ label: "Ideas take longer to develop", correct: false }, { label: "You need to understand real user problems before designing solutions", correct: true }, { label: "Empathy is the easiest step", correct: false }, { label: "Teachers require it as the first step", correct: false }] },
      { text: "A good problem statement is…", options: [{ label: "Vague and open-ended", correct: false }, { label: "As short as possible", correct: false }, { label: "Specific — it names who, what, and why", correct: true }, { label: "Written by the user, not the designer", correct: false }] },
      { text: "In the Ideate step, you should generate…", options: [{ label: "One perfect idea", correct: false }, { label: "Many ideas, including unusual ones", correct: true }, { label: "Only realistic ideas", correct: false }, { label: "Ideas that already exist", correct: false }] },
      { text: "Design thinking is described as 'non-linear' because…", options: [{ label: "Designers cannot draw straight lines", correct: false }, { label: "You can go back and repeat steps based on what you learn", correct: true }, { label: "It takes less time than linear processes", correct: false }, { label: "Non-linear is a newer and better term", correct: false }] },
    ],
  },

  // ── Lesson 6 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a8028",
    accentColor: "#DC2626",
    badge: "Grade 2 · Lesson 6 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Improving Designs",
    subtitle: "Learn how to evaluate an existing design and make it better through structured feedback.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="8" width="44" height="36" rx="4" fill="#FEF2F2" stroke="#DC2626" stroke-width="2"></rect><text x="26" y="22" text-anchor="middle" font-size="8" font-weight="700" fill="#DC2626" font-family="Nunito,sans-serif">RUBRIC</text><line x1="10" y1="28" x2="42" y2="28" stroke="#FECACA" stroke-width="1.5"></line><text x="26" y="38" text-anchor="middle" font-size="8" fill="#DC2626" font-family="Nunito,sans-serif">Does it work? ✓</text></svg>`, heading: "Evaluation: judging a design fairly", body: "To improve a design, you first evaluate it — assess what works well and what does not. Good designers use a structured rubric: Does it solve the problem? Is it safe? Is it easy to use? Does it look appropriate? Evaluation is not about being negative — it is about being constructive." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="16" width="18" height="22" rx="3" fill="#FECACA" stroke="#DC2626" stroke-width="2"></rect><text x="13" y="30" text-anchor="middle" font-size="8" font-weight="700" fill="#DC2626" font-family="Nunito,sans-serif">V1</text><line x1="22" y1="27" x2="30" y2="27" stroke="#DC2626" stroke-width="2"></line><polygon points="30,23 38,27 30,31" fill="#DC2626"></polygon><rect x="30" y="16" width="18" height="22" rx="3" fill="#DC2626"></rect><text x="39" y="30" text-anchor="middle" font-size="8" font-weight="700" fill="white" font-family="Nunito,sans-serif">V2</text></svg>`, heading: "Comparing version 1 to version 2", body: `Improvement means version 2 is better than version 1 in at least one measurable way. "Better" must be specific: stronger, lighter, cheaper, easier to use, safer. Vague improvements like "nicer" do not count — designers must explain exactly HOW and WHY it is better.` },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><polygon points="26,4 50,48 2,48" fill="#FEF2F2" stroke="#DC2626" stroke-width="2.5"></polygon><line x1="26" y1="18" x2="26" y2="32" stroke="#DC2626" stroke-width="3" stroke-linecap="round"></line><circle cx="26" cy="38" r="3" fill="#DC2626"></circle></svg>`, heading: "Failure is useful data", body: "When a design fails a test, that is not bad news — it is valuable information. The failure tells you exactly what to fix. The most successful products in history went through many failed prototypes first. Designers who fear failure rarely create great products." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="20" fill="none" stroke="#DC2626" stroke-width="3"></circle><polyline points="26,6 26,26 40,26" fill="none" stroke="#DC2626" stroke-width="3" stroke-linecap="round"></polyline></svg>`, heading: "The improvement cycle", body: "Build → Test → Identify weakness → Redesign → Rebuild → Test again. Each cycle should produce a measurably better version. Designers document every version so they can track progress and understand what changes made the difference." },
    ],
    revealLabel: "Explore — tap to see evaluation in action",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="8" width="44" height="36" rx="4" fill="#FEF2F2" stroke="#DC2626" stroke-width="2"></rect><text x="26" y="22" text-anchor="middle" font-size="9" font-weight="700" fill="#DC2626" font-family="Nunito,sans-serif">RUBRIC</text><text x="26" y="34" text-anchor="middle" font-size="8" fill="#DC2626" font-family="Nunito,sans-serif">1 2 3 4 ★</text></svg>`, name: "Evaluation rubric", desc: "A rubric is a scoring tool. Rate the design: Does it work? (1-4). Is it safe? (1-4). Is it easy to use? (1-4). Total = your evaluation score!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="16" width="18" height="22" rx="3" fill="#FECACA" stroke="#DC2626" stroke-width="2"></rect><text x="13" y="30" text-anchor="middle" font-size="9" font-weight="700" fill="#DC2626" font-family="Nunito,sans-serif">V1</text><polygon points="28,23 36,27 28,31" fill="#DC2626"></polygon><rect x="30" y="16" width="18" height="22" rx="3" fill="#DC2626"></rect><text x="39" y="30" text-anchor="middle" font-size="9" font-weight="700" fill="white" font-family="Nunito,sans-serif">V2</text></svg>`, name: "Before vs after", desc: "Always compare your improved version to the original. What specific thing is better? By how much?" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#FEF2F2" stroke="#DC2626" stroke-width="3" stroke-dasharray="4 2"></circle><circle cx="26" cy="26" r="8" fill="#DC2626"></circle></svg>`, name: "Find the weak point", desc: "Every design has a weakest part. Find it by testing. A chain is only as strong as its weakest link!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="6" width="40" height="40" rx="3" fill="#FEF2F2" stroke="#DC2626" stroke-width="2"></rect><line x1="12" y1="16" x2="40" y2="16" stroke="#DC2626" stroke-width="1.5"></line><line x1="12" y1="22" x2="40" y2="22" stroke="#FECACA" stroke-width="1.5"></line><line x1="12" y1="28" x2="40" y2="28" stroke="#FECACA" stroke-width="1.5"></line><text x="26" y="40" text-anchor="middle" font-size="8" fill="#DC2626" font-weight="700" font-family="Nunito,sans-serif">JOURNAL V1→V2</text></svg>`, name: "Document your versions", desc: "Keep a design journal. Sketch Version 1, write what failed, sketch Version 2 with the fix labeled." },
    ],
    dragLabel: "Activity — match each design problem to the right improvement strategy",
    dragChips: [
      { label: "Make it thicker", val: "Make it thicker" },
      { label: "Round the edges", val: "Round the edges" },
      { label: "Add a grip surface", val: "Add a grip surface" },
      { label: "Lighten the material", val: "Lighten the material" },
    ],
    dragZones: [
      { answer: "Make it thicker", label: "Part breaks easily", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><line x1="6" y1="18" x2="30" y2="18" stroke="#FCA5A5" stroke-width="1.5" stroke-dasharray="3 2"></line><text x="18" y="30" text-anchor="middle" font-size="8" fill="#FCA5A5" font-weight="700" font-family="Nunito,sans-serif">BREAKS</text></svg>` },
      { answer: "Round the edges", label: "Sharp corners hurt", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="6" y="6" width="24" height="24" fill="none" stroke="#FCA5A5" stroke-width="2"></rect><text x="18" y="38" text-anchor="middle" font-size="7" fill="#FCA5A5" font-weight="700" font-family="Nunito,sans-serif">SHARP</text></svg>` },
      { answer: "Add a grip surface", label: "Object slips", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><line x1="8" y1="10" x2="28" y2="28" stroke="#FCA5A5" stroke-width="2"></line><line x1="8" y1="20" x2="18" y2="28" stroke="#FCA5A5" stroke-width="1.5"></line><text x="18" y="36" text-anchor="middle" font-size="7" fill="#FCA5A5" font-weight="700" font-family="Nunito,sans-serif">SLIPS</text></svg>` },
      { answer: "Lighten the material", label: "Too heavy to use", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="14" r="10" fill="none" stroke="#FCA5A5" stroke-width="2"></circle><line x1="18" y1="24" x2="18" y2="34" stroke="#FCA5A5" stroke-width="2"></line><text x="18" y="36" text-anchor="middle" font-size="6" fill="#FCA5A5" font-weight="700" font-family="Nunito,sans-serif">HEAVY</text></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "Which is a MEASURABLE improvement?", options: [{ label: "It looks nicer", correct: false }, { label: "It is more modern", correct: false }, { label: "It is 30% lighter than Version 1", correct: true }, { label: "The color is better", correct: false }] },
      { text: "Why is prototype failure described as 'useful data'?", options: [{ label: "It is not useful — failure is always bad", correct: false }, { label: "It tells you exactly what to fix", correct: true }, { label: "It means you should give up", correct: false }, { label: "Failure makes the next attempt cheaper", correct: false }] },
      { text: "What is a design rubric?", options: [{ label: "A type of material used in prototypes", correct: false }, { label: "A scoring tool for evaluating design quality", correct: true }, { label: "A sketch of the improved version", correct: false }, { label: "A list of materials needed", correct: false }] },
      { text: "Why should designers document every version of their design?", options: [{ label: "To impress their teacher", correct: false }, { label: "To track what changes made improvements", correct: true }, { label: "Because it is required by the school", correct: false }, { label: "Documents are needed to print designs", correct: false }] },
    ],
  },

  // ── Lesson 7 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a8029",
    accentColor: "#B45309",
    badge: "Grade 2 · Lesson 7 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Model Building with Materials",
    subtitle: "Compare different materials for model building and choose the right one for your purpose.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="4" width="20" height="20" rx="3" fill="#B45309" opacity=".7"></rect><rect x="28" y="4" width="20" height="20" rx="3" fill="#B45309" opacity=".5"></rect><rect x="4" y="28" width="20" height="20" rx="3" fill="#B45309" opacity=".3"></rect><rect x="28" y="28" width="20" height="20" rx="3" fill="#B45309" opacity=".2"></rect></svg>`, heading: "Material properties matter", body: "Different materials have different properties: hardness, flexibility, weight, texture, and durability. A good designer chooses materials based on what the model needs to do — not just what is available. Choosing wrong materials is one of the most common design mistakes." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><ellipse cx="26" cy="36" rx="20" ry="7" fill="#B45309" opacity=".6"></ellipse><ellipse cx="26" cy="24" rx="13" ry="13" fill="#B45309"></ellipse></svg>`, heading: "Common model-building materials", body: "Clay: easy to shape, but soft and breakable. Cardboard: lightweight, easy to cut, not very strong. Craft sticks (popsicle sticks): strong for their size, can be glued into structures. Foam: lightweight, soft, good for curved shapes. Each has strengths and weaknesses." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="18" width="28" height="28" rx="2" fill="#B45309" opacity=".3" stroke="#B45309" stroke-width="2"></rect><polygon points="4,18 16,6 44,6 32,18" fill="#B45309" opacity=".5" stroke="#B45309" stroke-width="1.5"></polygon><polygon points="32,18 44,6 44,34 32,46" fill="#B45309" opacity=".7"></polygon><text x="18" y="36" text-anchor="middle" font-size="7" fill="#B45309" font-weight="700" font-family="Nunito,sans-serif">1:10</text></svg>`, heading: "Scale models", body: "Real objects like buildings and cars are too big to build as full models. Designers build scale models — smaller versions where every measurement is reduced by the same ratio. A 1:10 scale model means every part is 10 times smaller than the real thing." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#FEF3C7" stroke="#B45309" stroke-width="2.5"></circle><polyline points="14,26 22,34 38,18" fill="none" stroke="#B45309" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></polyline></svg>`, heading: "Testing your model", body: "Once built, a model should be tested against your original plan. Does it look right? Are the proportions correct? Does it stand up? Can it do what you designed it to do? Testing a model is how you find out if your design actually works before committing to expensive final materials." },
    ],
    revealLabel: "Explore — tap to compare model-building materials",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><ellipse cx="26" cy="36" rx="20" ry="7" fill="#B45309" opacity=".5"></ellipse><ellipse cx="26" cy="24" rx="13" ry="13" fill="#B45309"></ellipse></svg>`, name: "Clay", desc: "PROS: easy to shape. CONS: soft, cracks when dry. Best for: organic/curved shapes, early prototypes." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="10" width="40" height="32" rx="3" fill="#FEF3C7" stroke="#B45309" stroke-width="2"></rect><line x1="6" y1="22" x2="46" y2="22" stroke="#B45309" stroke-width="1.5"></line><line x1="6" y1="32" x2="46" y2="32" stroke="#B45309" stroke-width="1.5"></line></svg>`, name: "Cardboard", desc: "PROS: lightweight, cheap, easy to cut. CONS: weak under loads. Best for: walls, flat panels, boxes." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="14" width="40" height="6" rx="2" fill="#B45309"></rect><rect x="6" y="24" width="40" height="6" rx="2" fill="#92400E"></rect><rect x="6" y="34" width="40" height="6" rx="2" fill="#78350F"></rect></svg>`, name: "Craft sticks", desc: "PROS: strong for size, easy to glue, rigid. CONS: limited to straight shapes. Best for: bridges, towers, frames." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="10" width="40" height="32" rx="8" fill="#FEF3C7" stroke="#B45309" stroke-width="2"></rect><circle cx="18" cy="26" r="6" fill="#B45309" opacity=".3"></circle><circle cx="34" cy="26" r="6" fill="#B45309" opacity=".3"></circle></svg>`, name: "Foam sheets", desc: "PROS: very light, easy to cut. CONS: crushes under weight. Best for: walls, panels, vehicle bodies." },
    ],
    dragLabel: "Activity — match each material to its BEST use case",
    dragChips: [
      { label: "Clay", val: "Clay" },
      { label: "Cardboard", val: "Cardboard" },
      { label: "Craft sticks", val: "Craft sticks" },
      { label: "Foam", val: "Foam" },
    ],
    dragZones: [
      { answer: "Clay", label: "Curved animal model", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><ellipse cx="18" cy="22" rx="12" ry="10" fill="none" stroke="#FCD34D" stroke-width="2"></ellipse><circle cx="18" cy="12" r="8" fill="none" stroke="#FCD34D" stroke-width="2"></circle></svg>` },
      { answer: "Cardboard", label: "Building walls", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="4" y="4" width="28" height="28" rx="2" fill="none" stroke="#FCD34D" stroke-width="2"></rect><line x1="4" y1="14" x2="32" y2="14" stroke="#FCD34D" stroke-width="1.5"></line><line x1="4" y1="24" x2="32" y2="24" stroke="#FCD34D" stroke-width="1.5"></line></svg>` },
      { answer: "Craft sticks", label: "Bridge/tower frame", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><line x1="4" y1="30" x2="32" y2="30" stroke="#FCD34D" stroke-width="2.5"></line><line x1="10" y1="30" x2="10" y2="6" stroke="#FCD34D" stroke-width="2.5"></line><line x1="26" y1="30" x2="26" y2="6" stroke="#FCD34D" stroke-width="2.5"></line><line x1="10" y1="6" x2="26" y2="6" stroke="#FCD34D" stroke-width="2.5"></line><line x1="10" y1="6" x2="26" y2="30" stroke="#FCD34D" stroke-width="1.5"></line></svg>` },
      { answer: "Foam", label: "Car body panel", svgContent: `<svg width="36" height="28" viewBox="0 0 36 28"><rect x="2" y="6" width="32" height="16" rx="6" fill="none" stroke="#FCD34D" stroke-width="2"></rect><circle cx="9" cy="22" r="5" fill="none" stroke="#FCD34D" stroke-width="2"></circle><circle cx="27" cy="22" r="5" fill="none" stroke="#FCD34D" stroke-width="2"></circle></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "What is a 'scale model'?", options: [{ label: "A model that can be weighed", correct: false }, { label: "A smaller version where all measurements are reduced by the same ratio", correct: true }, { label: "A model made only from clay", correct: false }, { label: "A digital model on a computer screen", correct: false }] },
      { text: "You need to build a bridge that holds weight. Which material is BEST?", options: [{ label: "Clay", correct: false }, { label: "Foam sheets", correct: false }, { label: "Craft sticks glued together", correct: true }, { label: "Tissue paper", correct: false }] },
      { text: "Which material property means 'can bend without breaking'?", options: [{ label: "Hardness", correct: false }, { label: "Durability", correct: false }, { label: "Flexibility", correct: true }, { label: "Weight", correct: false }] },
      { text: "Why test your model against the original plan?", options: [{ label: "To find out if your design actually works", correct: true }, { label: "Because the plan must be destroyed after use", correct: false }, { label: "Testing is faster than building", correct: false }, { label: "Plans are always wrong and need updates", correct: false }] },
    ],
  },

  // ── Lesson 8 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a802a",
    accentColor: "#0891B2",
    badge: "Grade 2 · Lesson 8 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Observing Printed Objects",
    subtitle: "Examine real 3D-printed objects and analyze their design — surface, structure, and purpose.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="36" width="40" height="6" rx="2" fill="#0891B2" opacity=".3"></rect><rect x="6" y="28" width="40" height="6" rx="2" fill="#0891B2" opacity=".5"></rect><rect x="6" y="20" width="40" height="6" rx="2" fill="#0891B2" opacity=".7"></rect><rect x="6" y="12" width="40" height="6" rx="2" fill="#0891B2"></rect></svg>`, heading: "What you can learn from a printed object", body: "Examining a real 3D-printed object teaches you things no textbook can. You can feel the layer lines, observe how overhanging parts were supported, see where infill patterns are visible, and understand how the design was oriented on the print bed to reduce failure." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><polygon points="4,4 14,14 26,8 38,14 48,4 48,48 38,42 26,48 14,42 4,48" fill="#CFFAFE" stroke="#0891B2" stroke-width="2"></polygon><line x1="14" y1="14" x2="38" y2="14" stroke="#0891B2" stroke-width="1.5"></line><line x1="14" y1="28" x2="38" y2="28" stroke="#0891B2" stroke-width="1.5"></line><line x1="14" y1="42" x2="38" y2="42" stroke="#0891B2" stroke-width="1.5"></line></svg>`, heading: "Infill patterns: inside the object", body: "3D-printed objects are rarely solid plastic all the way through. They use internal patterns called infill — like a honeycomb, grid, or triangle pattern — to save material while maintaining strength. Higher infill percentage = heavier but stronger. Lower = lighter but more fragile." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="38" width="40" height="6" rx="1" fill="#0891B2"></rect><rect x="6" y="30" width="40" height="6" rx="1" fill="#0891B2" opacity=".7"></rect><rect x="6" y="22" width="40" height="6" rx="1" fill="#0891B2" opacity=".5"></rect><rect x="6" y="14" width="40" height="6" rx="1" fill="#0891B2" opacity=".3"></rect><text x="26" y="10" text-anchor="middle" font-size="7" fill="#0891B2" font-weight="700" font-family="Nunito,sans-serif">0.1mm layers</text></svg>`, heading: "Surface finish and layer resolution", body: "The layer height setting controls print quality. A 0.1mm layer height produces a smooth, detailed surface but takes longer. A 0.3mm layer height is faster but you can see individual layers. Designers choose layer height based on whether appearance or speed is more important." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="18" width="28" height="28" rx="2" fill="#CFFAFE" stroke="#0891B2" stroke-width="2"></rect><polygon points="4,18 16,6 44,6 32,18" fill="#0891B2" opacity=".4"></polygon><arrow><line x1="40" y1="28" x2="50" y2="28" stroke="#0891B2" stroke-width="2" stroke-dasharray="3 2"></line></arrow><text x="28" y="46" font-size="7" fill="#0891B2" font-weight="700" font-family="Nunito,sans-serif">↔ strong</text></svg>`, heading: "Weak points in 3D printed objects", body: "3D-printed parts are strong in the horizontal direction (along layers) but weaker in the vertical direction (between layers). This is called anisotropy. Smart designers orient their prints so that stress forces act along the layers, not across them." },
    ],
    revealLabel: "Explore — tap to examine 3D printing concepts",
    revealCards: [
      { frontSvg: `<svg width="52" height="36" viewBox="0 0 52 36"><rect x="2" y="4" width="48" height="6" rx="1" fill="#0891B2"></rect><rect x="2" y="12" width="48" height="6" rx="1" fill="#0891B2" opacity=".7"></rect><rect x="2" y="20" width="48" height="6" rx="1" fill="#0891B2" opacity=".5"></rect><rect x="2" y="28" width="48" height="6" rx="1" fill="#0891B2" opacity=".3"></rect></svg>`, name: "Layer lines", desc: "You can see and feel horizontal lines on a 3D print — each line is one layer of melted plastic, 0.1–0.3mm thick!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><polygon points="26,6 38,26 26,46 14,26" fill="#CFFAFE" stroke="#0891B2" stroke-width="2"></polygon><polygon points="26,14 34,26 26,38 18,26" fill="#0891B2" opacity=".4"></polygon><polygon points="26,22 30,26 26,30 22,26" fill="#0891B2"></polygon></svg>`, name: "Infill pattern", desc: "The inside of a 3D print uses a pattern like honeycomb or diamonds — saves plastic, keeps it strong!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="6" y="38" width="40" height="4" rx="1" fill="#0891B2"></rect><rect x="6" y="32" width="40" height="4" rx="1" fill="#0891B2" opacity=".7"></rect><rect x="6" y="26" width="40" height="4" rx="1" fill="#0891B2" opacity=".5"></rect><text x="26" y="22" text-anchor="middle" font-size="8" fill="#0891B2" font-weight="700" font-family="Nunito,sans-serif">0.1mm = smooth</text><text x="26" y="14" text-anchor="middle" font-size="8" fill="#0891B2" font-weight="700" font-family="Nunito,sans-serif">0.3mm = fast</text></svg>`, name: "Layer height", desc: "0.1mm = smooth but slow. 0.3mm = faster but layered look. You choose based on whether looks or speed matters more." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="18" width="44" height="24" rx="2" fill="#CFFAFE" stroke="#0891B2" stroke-width="2"></rect><line x1="4" y1="30" x2="48" y2="30" stroke="#0891B2" stroke-width="2.5" stroke-dasharray="4 2"></line><text x="26" y="16" text-anchor="middle" font-size="7" fill="#0891B2" font-weight="700" font-family="Nunito,sans-serif">↔ STRONG</text><text x="26" y="50" text-anchor="middle" font-size="7" fill="#EF4444" font-weight="700" font-family="Nunito,sans-serif">↕ WEAK</text></svg>`, name: "Print orientation", desc: "Prints are stronger sideways (along layers) than up-down (between layers). Orient your model so stress goes along the layers!" },
    ],
    dragLabel: "Activity — match each observation to what it tells you about the print",
    dragChips: [
      { label: "Layer height was small", val: "Layer height was small" },
      { label: "Infill was low", val: "Infill was low" },
      { label: "Poor orientation", val: "Poor orientation" },
      { label: "Good support used", val: "Good support used" },
    ],
    dragZones: [
      { answer: "Layer height was small", label: "Surface is very smooth", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="4" y="10" width="28" height="20" rx="8" fill="none" stroke="#67E8F9" stroke-width="2"></rect><text x="18" y="26" text-anchor="middle" font-size="8" fill="#67E8F9" font-weight="700" font-family="Nunito,sans-serif">SMOOTH</text></svg>` },
      { answer: "Infill was low", label: "Part is light but fragile", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><circle cx="18" cy="18" r="13" fill="none" stroke="#67E8F9" stroke-width="2"></circle><text x="18" y="22" text-anchor="middle" font-size="7" fill="#67E8F9" font-weight="700" font-family="Nunito,sans-serif">LIGHT/FRAGILE</text></svg>` },
      { answer: "Poor orientation", label: "Part snapped between layers", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="4" y="4" width="28" height="12" rx="2" fill="none" stroke="#67E8F9" stroke-width="2"></rect><line x1="4" y1="20" x2="32" y2="20" stroke="#EF4444" stroke-width="2" stroke-dasharray="3 2"></line><rect x="4" y="22" width="28" height="12" rx="2" fill="none" stroke="#67E8F9" stroke-width="2"></rect></svg>` },
      { answer: "Good support used", label: "Overhang printed cleanly", svgContent: `<svg width="36" height="36" viewBox="0 0 36 36"><rect x="4" y="4" width="28" height="14" rx="2" fill="none" stroke="#67E8F9" stroke-width="2"></rect><line x1="4" y1="18" x2="4" y2="32" stroke="#67E8F9" stroke-width="1.5" stroke-dasharray="2 2"></line><line x1="18" y1="18" x2="18" y2="32" stroke="#67E8F9" stroke-width="1.5" stroke-dasharray="2 2"></line><line x1="32" y1="18" x2="32" y2="32" stroke="#67E8F9" stroke-width="1.5" stroke-dasharray="2 2"></line></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "3D printed objects are WEAKER in which direction?", options: [{ label: "Along the layers (horizontal)", correct: false }, { label: "Between the layers (vertical)", correct: true }, { label: "Diagonally", correct: false }, { label: "They are equally strong in all directions", correct: false }] },
      { text: "A lower infill percentage means the object is…", options: [{ label: "Stronger and heavier", correct: false }, { label: "Heavier but weaker", correct: false }, { label: "Lighter but more fragile", correct: true }, { label: "Faster to design", correct: false }] },
      { text: "To get a very smooth surface finish, you should use…", options: [{ label: "A high layer height (0.3mm)", correct: false }, { label: "A low layer height (0.1mm)", correct: true }, { label: "More infill", correct: false }, { label: "Larger nozzle size", correct: false }] },
      { text: "Why is print orientation important?", options: [{ label: "It affects the color of the print", correct: false }, { label: "It determines which side faces the user", correct: false }, { label: "It controls where stress forces act relative to layer direction", correct: true }, { label: "Orientation affects how long the file takes to send", correct: false }] },
    ],
  },

  // ── Lesson 9 ──────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a802b",
    accentColor: "#7C3AED",
    badge: "Grade 2 · Lesson 9 of 10 · Maker Stage",
    typeBadge: "Activity",
    title: "Testing Simple Models",
    subtitle: "Design and conduct structured tests on your models — and use results to make better designs.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="18" y="6" width="16" height="36" rx="4" fill="#7C3AED"></rect><ellipse cx="26" cy="42" rx="10" ry="5" fill="#5B21B6"></ellipse><circle cx="26" cy="6" r="5" fill="#C4B5FD"></circle></svg>`, heading: "Why testing is not optional", body: "Untested designs are just guesses. Testing turns guesses into knowledge. A bridge model must be tested with actual weight. A container must be tested for leakage. A vehicle must be tested on the actual surface it will travel. Testing reveals what theory cannot predict." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><line x1="6" y1="26" x2="46" y2="26" stroke="#7C3AED" stroke-width="3" stroke-linecap="round"></line><circle cx="14" cy="26" r="6" fill="#7C3AED"></circle><circle cx="38" cy="26" r="6" fill="#EDE9FE" stroke="#7C3AED" stroke-width="2.5"></circle><text x="14" y="42" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">CHANGE</text><text x="38" y="42" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">SAME</text></svg>`, heading: "Fair testing: controlling variables", body: "A fair test changes only one thing at a time. If you want to know whether a thicker wall makes a model stronger, only change the wall thickness — keep everything else the same. If you change two things at once, you cannot know which change made the difference." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="8" width="44" height="36" rx="3" fill="#EDE9FE" stroke="#7C3AED" stroke-width="2"></rect><line x1="16" y1="8" x2="16" y2="44" stroke="#7C3AED" stroke-width="1.5"></line><line x1="32" y1="8" x2="32" y2="44" stroke="#7C3AED" stroke-width="1.5"></line><text x="10" y="22" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">TEST</text><text x="24" y="22" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">EXP.</text><text x="40" y="22" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">ACTUAL</text></svg>`, heading: "Recording test results", body: "Test results must be written down systematically: what you tested, what you expected, what actually happened, and what you conclude. Without records, you forget what worked and repeat the same mistakes. A simple table is the best format for recording test data." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="14" cy="26" r="10" fill="#7C3AED" opacity=".4"></circle><line x1="24" y1="26" x2="28" y2="26" stroke="#7C3AED" stroke-width="2.5"></line><polygon points="28,22 38,26 28,30" fill="#7C3AED"></polygon><circle cx="40" cy="26" r="10" fill="#7C3AED"></circle></svg>`, heading: "Using results to redesign", body: "Test results directly drive redesign decisions. If the roof of your model collapses under 200g of weight but you need it to hold 500g, you know you need a stronger structure. The test result — not your opinion — drives the design change. This is engineering thinking." },
    ],
    revealLabel: "Explore — tap to learn about structured testing",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="8" y="8" width="36" height="36" rx="3" fill="#EDE9FE" stroke="#7C3AED" stroke-width="2"></rect><line x1="14" y1="18" x2="38" y2="18" stroke="#7C3AED" stroke-width="1.5"></line><line x1="14" y1="26" x2="30" y2="26" stroke="#C4B5FD" stroke-width="1.5"></line><text x="26" y="38" text-anchor="middle" font-size="8" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">TEST PLAN</text></svg>`, name: "Test plan", desc: "Before testing: write what you are testing, what you expect to happen, and how you will measure the result." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="20" fill="#EDE9FE" stroke="#7C3AED" stroke-width="2.5"></circle><line x1="14" y1="26" x2="38" y2="26" stroke="#7C3AED" stroke-width="2"></line><text x="26" y="20" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">CHANGE 1</text><text x="26" y="36" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">THING ONLY</text></svg>`, name: "Fair test", desc: "Change only ONE thing at a time. Keep all other conditions the same. Otherwise your results are unreliable!" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><rect x="4" y="8" width="44" height="36" rx="3" fill="#EDE9FE" stroke="#7C3AED" stroke-width="2"></rect><line x1="16" y1="8" x2="16" y2="44" stroke="#7C3AED" stroke-width="1"></line><line x1="32" y1="8" x2="32" y2="44" stroke="#7C3AED" stroke-width="1"></line><text x="10" y="26" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">↓</text><text x="24" y="26" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">↓</text><text x="40" y="26" text-anchor="middle" font-size="7" fill="#7C3AED" font-weight="700" font-family="Nunito,sans-serif">↓</text></svg>`, name: "Record results", desc: "Write what happened in a table: Test → Expected → Actual → Conclusion. Never rely on memory." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="16" cy="26" r="10" fill="#7C3AED" opacity=".4" stroke="#7C3AED" stroke-width="2"></circle><line x1="26" y1="26" x2="30" y2="26" stroke="#7C3AED" stroke-width="2.5"></line><polygon points="30,22 40,26 30,30" fill="#7C3AED"></polygon><circle cx="42" cy="26" r="8" fill="#7C3AED"></circle><text x="42" y="30" text-anchor="middle" font-size="7" fill="white" font-weight="700" font-family="Nunito,sans-serif">V2</text></svg>`, name: "Redesign from data", desc: 'Let the test results — not opinions — drive your changes. "The data shows the wall needs to be 5mm thicker."' },
    ],
    dragLabel: "Put the testing process steps in order",
    dragChips: [
      { label: "Write a test plan", val: "Write a test plan" },
      { label: "Build the model", val: "Build the model" },
      { label: "Run the test", val: "Run the test" },
      { label: "Record results", val: "Record results" },
    ],
    dragZones: [
      { answer: "Write a test plan", label: "Step 1", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>` },
      { answer: "Build the model", label: "Step 2", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>` },
      { answer: "Run the test", label: "Step 3", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>` },
      { answer: "Record results", label: "Step 4", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#7C3AED"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">4</text></svg>` },
    ],
    quizLabel: "Quiz — challenge yourself!",
    quiz: [
      { text: "What is a 'fair test'?", options: [{ label: "A test everyone agrees is fair", correct: false }, { label: "A test that changes only one variable at a time", correct: true }, { label: "A test that always gives a passing result", correct: false }, { label: "A test done by two students together", correct: false }] },
      { text: "Why must test results be written down?", options: [{ label: "Because teachers require it", correct: false }, { label: "So you can remember what worked and avoid repeating mistakes", correct: true }, { label: "Written results are more accurate than remembered results", correct: false }, { label: "Results must be typed, not handwritten", correct: false }] },
      { text: "Your tower model collapses at 300g but needs to hold 600g. What should you do?", options: [{ label: "Accept 300g as good enough", correct: false }, { label: "Change the color of the model", correct: false }, { label: "Use test data to identify the weakest part and redesign it", correct: true }, { label: "Build an entirely new model from scratch", correct: false }] },
      { text: "Which is a data-driven redesign decision?", options: [{ label: `"I think it would look better wider"`, correct: false }, { label: `"My friend said it needs more color"`, correct: false }, { label: `"The test showed the base collapsed first, so I doubled the base thickness"`, correct: true }, { label: `"Version 2 should just be completely different"`, correct: false }] },
    ],
  },

  // ── Lesson 10 ─────────────────────────────────────────────────────────────
  {
    id: "69ddc685f048754ba85a802c",
    accentColor: "#BE185D",
    badge: "Grade 2 · Lesson 10 of 10 · Maker Stage",
    typeBadge: "Project",
    title: "Classroom Problem Design Project",
    subtitle: "Identify a real problem in your classroom, design a solution, build it, test it, and present your findings.",
    readings: [
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>`, heading: "Phase 1 — Problem discovery (Empathize + Define)", body: `Spend time in your classroom observing and interviewing classmates. What frustrates them? What is missing? What takes too long? Choose ONE specific problem and write a clear problem statement: "Students in Grade 2 need a way to [specific action] because [specific reason]."` },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>`, heading: "Phase 2 — Design and sketch (Ideate)", body: "Generate at least THREE different design ideas — no matter how simple or silly. For each idea, sketch it and list: what shapes it uses, what materials you would need, and one advantage and one disadvantage. Then choose the best idea and explain why." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>`, heading: "Phase 3 — Build and test (Prototype + Test)", body: "Build your chosen design using available materials (clay, cardboard, craft sticks, foam). Document your build process with sketches. Then test it: does it solve the original problem? Measure or observe what works and what does not. Record everything." },
      { svgIcon: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">4</text></svg>`, heading: "Phase 4 — Improve and present", body: "Based on your test results, make at least ONE specific improvement to your model. Then prepare a short presentation: state the problem, explain your design, show what the test results were, describe your improvement, and reflect on what you would do differently." },
    ],
    revealLabel: "Explore — review all design process phases",
    revealCards: [
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>`, name: "Empathize + Define", desc: "Observe → interview → write problem statement. The best solutions start with the deepest understanding of the problem." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>`, name: "Ideate", desc: "3+ sketched ideas, each with shapes listed, pros, cons. Then pick ONE and justify your choice." },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>`, name: "Prototype + Test", desc: "Build it. Test it. Record actual data: does it work? what failed? what held up?" },
      { frontSvg: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">4</text></svg>`, name: "Improve + Present", desc: "Make one data-driven improvement. Then present: problem → design → test results → improvement → reflection." },
    ],
    dragLabel: "Put the complete design project phases in order",
    dragChips: [
      { label: "Empathize", val: "Empathize" },
      { label: "Define problem", val: "Define problem" },
      { label: "Ideate 3+ ideas", val: "Ideate 3+ ideas" },
      { label: "Build prototype", val: "Build prototype" },
    ],
    dragZones: [
      { answer: "Empathize", label: "Phase 1", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">1</text></svg>` },
      { answer: "Define problem", label: "Phase 2", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">2</text></svg>` },
      { answer: "Ideate 3+ ideas", label: "Phase 3", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">3</text></svg>` },
      { answer: "Build prototype", label: "Phase 4", svgContent: `<svg width="52" height="52" viewBox="0 0 52 52"><circle cx="26" cy="26" r="22" fill="#BE185D"></circle><text x="26" y="34" text-anchor="middle" font-size="26" font-weight="900" fill="white" font-family="Nunito,sans-serif">4</text></svg>` },
    ],
    quizLabel: "Final project quiz — demonstrate your full Grade 2 learning!",
    quiz: [
      { text: "Your problem statement should be specific because…", options: [{ label: "Specific problems sound more impressive", correct: false }, { label: "Specific problems lead to more focused and effective solutions", correct: true }, { label: "Teachers give better grades for specific statements", correct: false }, { label: "Short statements are always more specific", correct: false }] },
      { text: "Why generate THREE design ideas instead of just one?", options: [{ label: "Three takes up more paper", correct: false }, { label: "Your first idea is rarely the best — comparing options leads to better choices", correct: true }, { label: "Three is the required number by design rules", correct: false }, { label: "More ideas means a longer presentation", correct: false }] },
      { text: "In your presentation, why must you show test RESULTS (not just your opinion)?", options: [{ label: "Results sound more scientific", correct: false }, { label: "Results prove your design was built correctly", correct: false }, { label: "Results are objective evidence that your improvement is real — not just a guess", correct: true }, { label: "Presentations always need data tables", correct: false }] },
      { text: "What makes a project 'improvement' valid in engineering?", options: [{ label: "The designer says it is better", correct: false }, { label: "It looks more polished", correct: false }, { label: "It is measurably better in a specific way based on test data", correct: true }, { label: "The teacher approves the improvement", correct: false }] },
    ],
  },
];